// Mock data for UI preview — no database required
// Replace with real Prisma calls once you connect PostgreSQL

export const mockPosts = [
  {
    id: "post-1",
    title: "Building Scalable Microservices with Node.js",
    slug: "building-scalable-microservices-with-nodejs",
    excerpt: "Learn how to architect and deploy production-ready microservices using Node.js, Docker, and Kubernetes.",
    body: `# Building Scalable Microservices with Node.js\n\nMicroservices architecture has become the go-to approach for building large-scale applications.\n\n## Why Microservices?\n\n- **Independent deployment** — each service can be deployed separately\n- **Technology flexibility** — use the right tool for each job\n- **Fault isolation** — failures don't cascade\n\n## Getting Started\n\n\`\`\`javascript\nconst express = require('express');\nconst app = express();\napp.get('/health', (req, res) => res.json({ status: 'ok' }));\napp.listen(3000);\n\`\`\``,
    category: "Engineering",
    author: "Engineers Door Team",
    readTime: "8 min read",
    icon: "⚙️",
    gradient: "from-cyan-500 to-blue-600",
    published: true,
    createdAt: new Date("2025-04-10T09:00:00Z"),
    updatedAt: new Date("2025-04-10T09:00:00Z"),
  },
  {
    id: "post-2",
    title: "Cloud Cost Optimization Strategies for 2025",
    slug: "cloud-cost-optimization-strategies-2025",
    excerpt: "Practical strategies to reduce your AWS, GCP, or Azure bill without sacrificing performance.",
    body: `# Cloud Cost Optimization Strategies for 2025\n\nCloud costs can spiral out of control quickly. Here are proven strategies to keep them in check.\n\n## Right-sizing Resources\n\nAnalyze your actual usage and downsize over-provisioned instances.\n\n## Reserved Instances\n\nCommit to 1-3 year terms for predictable workloads and save up to 72%.`,
    category: "Cloud",
    author: "Cloud Team",
    readTime: "6 min read",
    icon: "☁️",
    gradient: "from-indigo-500 to-purple-600",
    published: true,
    createdAt: new Date("2025-04-05T11:00:00Z"),
    updatedAt: new Date("2025-04-05T11:00:00Z"),
  },
  {
    id: "post-3",
    title: "Zero Trust Security Model Explained",
    slug: "zero-trust-security-model-explained",
    excerpt: "Understanding the Zero Trust security model and how to implement it in your organization.",
    body: `# Zero Trust Security Model\n\n"Never trust, always verify" — this is the core principle of Zero Trust.\n\n## Key Principles\n\n1. Verify every user and device\n2. Least privilege access\n3. Assume breach mentality`,
    category: "Security",
    author: "Security Team",
    readTime: "10 min read",
    icon: "🔐",
    gradient: "from-orange-500 to-red-500",
    published: false,
    createdAt: new Date("2025-03-28T14:00:00Z"),
    updatedAt: new Date("2025-03-28T14:00:00Z"),
  },
  {
    id: "post-4",
    title: "Getting Started with Kubernetes in Production",
    slug: "getting-started-with-kubernetes-in-production",
    excerpt: "A practical guide to deploying and managing containerized workloads with Kubernetes.",
    body: `# Kubernetes in Production\n\nKubernetes is the de facto standard for container orchestration.\n\n## Core Concepts\n\n- Pods, Deployments, Services\n- ConfigMaps and Secrets\n- Ingress controllers`,
    category: "DevOps",
    author: "DevOps Team",
    readTime: "12 min read",
    icon: "🐳",
    gradient: "from-green-500 to-teal-500",
    published: true,
    createdAt: new Date("2025-03-20T08:00:00Z"),
    updatedAt: new Date("2025-03-20T08:00:00Z"),
  },
  {
    id: "post-5",
    title: "AI-Powered Code Review: The Future of Engineering",
    slug: "ai-powered-code-review-future-of-engineering",
    excerpt: "How AI tools are transforming the code review process and improving software quality.",
    body: `# AI-Powered Code Review\n\nAI is changing how we write and review code.\n\n## Tools to Watch\n\n- GitHub Copilot\n- Amazon CodeWhisperer\n- Tabnine`,
    category: "AI/ML",
    author: "AI Research Team",
    readTime: "7 min read",
    icon: "🤖",
    gradient: "from-purple-500 to-pink-500",
    published: true,
    createdAt: new Date("2025-03-15T10:00:00Z"),
    updatedAt: new Date("2025-03-15T10:00:00Z"),
  },
  {
    id: "post-6",
    title: "TypeScript Best Practices for Large Teams",
    slug: "typescript-best-practices-large-teams",
    excerpt: "Patterns and conventions that keep TypeScript codebases maintainable as your team grows.",
    body: `# TypeScript Best Practices\n\nTypeScript shines in large codebases. Here's how to get the most out of it.\n\n## Strict Mode\n\nAlways enable strict mode in tsconfig.json.\n\n## Utility Types\n\nLearn Partial, Required, Pick, Omit, and Record.`,
    category: "Web Development",
    author: "Frontend Team",
    readTime: "9 min read",
    icon: "📘",
    gradient: "from-blue-500 to-cyan-400",
    published: false,
    createdAt: new Date("2025-03-10T16:00:00Z"),
    updatedAt: new Date("2025-03-10T16:00:00Z"),
  },
];

export const mockJobs = [
  {
    id: "job-1",
    title: "Senior Full Stack Engineer",
    department: "Engineering",
    type: "Full-time",
    location: "Remote",
    techTags: ["React", "Node.js", "TypeScript", "PostgreSQL", "AWS"],
    active: true,
    createdAt: new Date("2025-04-08T09:00:00Z"),
    updatedAt: new Date("2025-04-08T09:00:00Z"),
  },
  {
    id: "job-2",
    title: "DevOps Engineer",
    department: "DevOps",
    type: "Full-time",
    location: "Hybrid",
    techTags: ["Kubernetes", "Docker", "Terraform", "AWS", "CI/CD"],
    active: true,
    createdAt: new Date("2025-04-06T10:00:00Z"),
    updatedAt: new Date("2025-04-06T10:00:00Z"),
  },
  {
    id: "job-3",
    title: "Cloud Solutions Architect",
    department: "Cloud",
    type: "Contract",
    location: "Remote",
    techTags: ["AWS", "GCP", "Azure", "Terraform", "Architecture"],
    active: false,
    createdAt: new Date("2025-03-25T11:00:00Z"),
    updatedAt: new Date("2025-03-25T11:00:00Z"),
  },
  {
    id: "job-4",
    title: "Frontend Engineer (React)",
    department: "Frontend",
    type: "Full-time",
    location: "Remote",
    techTags: ["React", "Next.js", "TypeScript", "Tailwind CSS", "GraphQL"],
    active: true,
    createdAt: new Date("2025-03-20T09:00:00Z"),
    updatedAt: new Date("2025-03-20T09:00:00Z"),
  },
  {
    id: "job-5",
    title: "Machine Learning Engineer",
    department: "AI/ML",
    type: "Full-time",
    location: "On-site",
    techTags: ["Python", "TensorFlow", "PyTorch", "MLOps", "GCP"],
    active: true,
    createdAt: new Date("2025-03-15T14:00:00Z"),
    updatedAt: new Date("2025-03-15T14:00:00Z"),
  },
  {
    id: "job-6",
    title: "Security Engineer",
    department: "Security",
    type: "Part-time",
    location: "Hybrid",
    techTags: ["Penetration Testing", "SIEM", "Zero Trust", "AWS Security"],
    active: false,
    createdAt: new Date("2025-03-10T08:00:00Z"),
    updatedAt: new Date("2025-03-10T08:00:00Z"),
  },
];

export const mockProjects = [
  {
    id: "proj-1",
    title: "FinTech Payment Platform",
    category: "Web Application",
    description: "Built a high-throughput payment processing platform handling 50,000+ transactions per day with 99.99% uptime SLA for a leading financial services company.",
    result: "99.99% uptime · 50K+ daily transactions",
    techTags: ["Node.js", "React", "PostgreSQL", "Redis", "AWS", "Stripe"],
    icon: "💳",
    gradient: "from-green-500 to-teal-500",
    createdAt: new Date("2025-02-15T09:00:00Z"),
    updatedAt: new Date("2025-02-15T09:00:00Z"),
  },
  {
    id: "proj-2",
    title: "E-commerce Platform Migration",
    category: "Cloud Infrastructure",
    description: "Migrated a legacy monolithic e-commerce platform to microservices on AWS, reducing infrastructure costs by 40% and enabling 3x faster feature deployments.",
    result: "40% cost reduction · 3x faster deploys",
    techTags: ["AWS", "Docker", "Kubernetes", "Next.js", "MongoDB"],
    icon: "🛒",
    gradient: "from-purple-500 to-cyan-500",
    createdAt: new Date("2025-01-20T10:00:00Z"),
    updatedAt: new Date("2025-01-20T10:00:00Z"),
  },
  {
    id: "proj-3",
    title: "AI-Powered Analytics Dashboard",
    category: "AI/ML",
    description: "Developed a real-time analytics dashboard with ML-powered insights for a SaaS company, enabling data-driven decisions for 10,000+ users.",
    result: "10K+ users · 60% faster insights",
    techTags: ["Python", "TensorFlow", "React", "FastAPI", "GCP"],
    icon: "🤖",
    gradient: "from-cyan-500 to-blue-600",
    createdAt: new Date("2024-12-10T11:00:00Z"),
    updatedAt: new Date("2024-12-10T11:00:00Z"),
  },
  {
    id: "proj-4",
    title: "Healthcare Patient Portal",
    category: "Web Application",
    description: "Designed and built a HIPAA-compliant patient portal with real-time appointment scheduling, telemedicine integration, and secure messaging.",
    result: "HIPAA compliant · 25K active patients",
    techTags: ["React", "Node.js", "PostgreSQL", "WebRTC", "Azure"],
    icon: "🏥",
    gradient: "from-pink-500 to-rose-500",
    createdAt: new Date("2024-11-05T09:00:00Z"),
    updatedAt: new Date("2024-11-05T09:00:00Z"),
  },
  {
    id: "proj-5",
    title: "DevOps Automation Pipeline",
    category: "DevOps",
    description: "Built a fully automated CI/CD pipeline with infrastructure-as-code, reducing deployment time from 2 hours to under 8 minutes.",
    result: "2hrs → 8min deployments · Zero downtime",
    techTags: ["Terraform", "GitHub Actions", "Docker", "Kubernetes", "AWS"],
    icon: "🚀",
    gradient: "from-orange-500 to-red-500",
    createdAt: new Date("2024-10-18T14:00:00Z"),
    updatedAt: new Date("2024-10-18T14:00:00Z"),
  },
  {
    id: "proj-6",
    title: "Real-time Logistics Tracker",
    category: "Mobile App",
    description: "Built a cross-platform mobile app for real-time fleet tracking and logistics management, serving 500+ drivers across 12 cities.",
    result: "500+ drivers · 30% fuel savings",
    techTags: ["React Native", "Node.js", "WebSockets", "MongoDB", "Google Maps"],
    icon: "🚚",
    gradient: "from-indigo-500 to-purple-600",
    createdAt: new Date("2024-09-22T10:00:00Z"),
    updatedAt: new Date("2024-09-22T10:00:00Z"),
  },
];

export const mockContacts = [
  {
    id: "contact-1",
    name: "Sarah Johnson",
    email: "sarah@techcorp.com",
    subject: "Partnership Inquiry",
    message: "Hi, I'm interested in exploring a potential partnership between our companies. We're looking for a reliable IT partner for our digital transformation initiative. We have a team of 200+ engineers and are looking to modernize our infrastructure. Could we schedule a call to discuss the possibilities?",
    read: false,
    createdAt: new Date("2025-05-13T08:30:00Z"),
  },
  {
    id: "contact-2",
    name: "Michael Chen",
    email: "m.chen@startup.io",
    subject: "Custom Software Development Quote",
    message: "We need a custom CRM system built from scratch. Our team is 50 people and we have specific workflow requirements that off-the-shelf solutions don't cover. What's your typical timeline and pricing for such a project? We'd like to get started within the next 2 months.",
    read: false,
    createdAt: new Date("2025-05-12T14:15:00Z"),
  },
  {
    id: "contact-3",
    name: "Emma Williams",
    email: "emma@enterprise.com",
    subject: "Cloud Migration Project",
    message: "We're planning to migrate our on-premise infrastructure to AWS. We have about 200 servers and need help with the migration strategy and execution. Our deadline is Q3 2025. Are you available for an initial consultation next week?",
    read: true,
    createdAt: new Date("2025-05-11T10:00:00Z"),
  },
  {
    id: "contact-4",
    name: "David Park",
    email: "d.park@fintech.co",
    subject: "Security Audit Request",
    message: "Our fintech startup is preparing for a Series B round and investors require a comprehensive security audit. We need penetration testing, code review, and compliance assessment (SOC 2, PCI DSS). Can you provide a proposal?",
    read: true,
    createdAt: new Date("2025-05-10T16:45:00Z"),
  },
  {
    id: "contact-5",
    name: "Aisha Patel",
    email: "aisha@retailco.com",
    subject: "E-commerce Platform Rebuild",
    message: "Our current e-commerce platform is struggling to handle our growth — we're doing 10K orders/day and the system keeps crashing. We need a complete rebuild with better scalability. Budget is flexible for the right team.",
    read: false,
    createdAt: new Date("2025-05-09T09:20:00Z"),
  },
  {
    id: "contact-6",
    name: "James Rodriguez",
    email: "james@logistics.net",
    subject: "Mobile App Development",
    message: "We need a mobile app for our delivery drivers — real-time tracking, route optimization, proof of delivery with photo capture. iOS and Android. We have about 300 drivers. What's your experience with React Native?",
    read: true,
    createdAt: new Date("2025-05-08T11:30:00Z"),
  },
  {
    id: "contact-7",
    name: "Lisa Thompson",
    email: "lisa@healthtech.io",
    subject: "HIPAA Compliance Consulting",
    message: "We're building a telehealth platform and need guidance on HIPAA compliance — architecture review, data encryption, audit logging, and BAA agreements. Do you have experience in the healthcare tech space?",
    read: false,
    createdAt: new Date("2025-05-07T13:00:00Z"),
  },
];

// Aggregated stats for dashboard
export const mockStats = {
  totalPosts: mockPosts.length,
  publishedPosts: mockPosts.filter((p) => p.published).length,
  totalJobs: mockJobs.length,
  activeJobs: mockJobs.filter((j) => j.active).length,
  totalProjects: mockProjects.length,
  totalContacts: mockContacts.length,
  unreadContacts: mockContacts.filter((c) => !c.read).length,
  recentPosts: mockPosts.slice(0, 3),
  recentJobs: mockJobs.slice(0, 3),
  recentContacts: mockContacts.slice(0, 3),
};
